server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-api
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/**
        - id: order-api
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/orders/**
